import Navbar from "../components/navbar"
import Footer from "../components/footer"
import Menu from "../components/menu"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 

{

  return (
<html lang="en">
      <body className="min-h-screen flex flex-col">
      <Navbar />
    
      {children}
      <Footer/>
      </body>
</html>
  )
}
